### ISSUE TITLE
opensea 发offer的参数问题

### ISSUE THREAD

**Issue by kkthmyh** [casiphia/opensea-go#1]
orders_create.go的给NFT发offer的方法
OrdersCreateOffers，向opensea api请求参数的时候，那个post请求体中的signature参数具体是怎么生成的呢？看了seaport的文档也没具体说明，目前看到主流的给NFT发offer的代码主要还是用的官方的seaport.js SDK来实现的，想知道golang怎么去生成这个signature，期盼回复，谢谢

**Comment by casiphia** [comment]
signature是钱包签名的数据，前端调用web3接口签名后，将签名数据下发给后端，opensea接口要对签名校验

**Comment by kkthmyh** [comment]
我现在就想做一个后端自动发offer的服务，不通过前端进行签名，就golang后端进行私钥+内容进行签名，但是我尝试后端签名后，调用api后报签名错误

**Comment by casiphia** [comment]
golang使用的签名算法库与web3的签名算法库有差异的,请注意版本,web3签名出来的数据s、r、v数据中，v有时候是27，有时候是28，而golang的签名算法中只有28，详细你可以查看源代码
